[workspace]
resolver = "3"
members = [
    "dial9-core",
    "dial9-tokio-telemetry",
    "dial9-trace-format",
    "dial9-trace-format-derive",
    "dial9-viewer-extension",
    "dial9-viewer-extension-macros",
    "dial9-macro",
    "dial9-metrique",
    "dial9-viewer",
    "dial9",
    "dial9-utils",
    "perf-self-profile",
    "examples/metrics-service",
    "examples/simple-local",
    "examples/memory-local",
    "examples/viewer-extension-demo",
]
exclude = [
    "dial9-trace-format/fuzz",
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/dial9-rs/dial9"

[workspace.dependencies]
libc = "0.2"
dial9-core = { version = "0.5.0-rc0", path = "dial9-core" }
dial9-utils = { version = "0.5.0-rc0", path = "dial9-utils" }
dial9-perf-self-profile = { version = "0.5.0-rc0", path = "perf-self-profile" }
dial9-trace-format = { version = "0.5.0-rc0", path = "dial9-trace-format" }
dial9-trace-format-derive = { version = "0.5.0-rc0", path = "dial9-trace-format-derive" }
dial9-viewer-extension = { version = "0.5.0-rc0", path = "dial9-viewer-extension" }
dial9-viewer-extension-macros = { version = "0.5.0-rc0", path = "dial9-viewer-extension-macros" }
dial9-macro = { version = "0.5.0-rc0", path = "dial9-macro" }
dial9-metrique = { version = "0.5.0-rc0", path = "dial9-metrique" }
assert2 = "0.4"

[profile.release]
debug = 1

[profile.viewer-extension]
inherits = "release"
opt-level = "z"
debug = 0
strip = "symbols"
lto = true
codegen-units = 1
panic = "abort"
