[package]
name = "telemetry-test-app"
edition = "2024"
version = "0.1.0"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.52.0", default-features = false, features = ["time"] }
dial9 = { path = "../../dial9", default-features = false, features = ["tokio"] }
dial9-utils = { path = "../../dial9-utils", features = ["span"] }

[target.'cfg(target_os = "linux")'.dependencies]
dial9 = { path = "../../dial9", default-features = false, features = [
    "tokio",
    "cpu-profiling",
    "taskdump",
] }
